// <auto-generated />
namespace JalaFoundation.Dev23.Wedding.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class presentList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(presentList));
        
        string IMigrationMetadata.Id
        {
            get { return "201801180559222_presentList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
