namespace JalaFoundation.Dev23.Wedding.DAL.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;
    using JalaFoundation.Dev23.Wedding.DAL.Models;
    using System.Data.Entity.Validation;

    internal sealed class Configuration : DbMigrationsConfiguration<JalaFoundation.Dev23.Wedding.DAL.WeddingContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(JalaFoundation.Dev23.Wedding.DAL.WeddingContext context)
        {
            #region Persons
            context.Persons.AddOrUpdate(x => x.PersonID,
            new Person() { PersonID = 1, FirstName = "Amalia", LastName = "Alfaro", CI = 7458614, Direction = "3524 West Fork Street", Mail = "Amalia.Alfaro@gmail.com", Telephone = 75523586 },
            new Person() { PersonID = 2, FirstName = "Gabriel", LastName = "Gomez", CI = 6589214, Direction = "Calle Padre Melgar N°222 (Zona El Cristo)", Mail = "Gabrie.Gomez@gmail.com", Telephone = 60325478 },
            new Person() { PersonID = 3, FirstName = "Carlos", LastName = "Tirado", CI = 7425338, Direction = "Av.José Ballivian # 705 Ed. COMTECO PB", Mail = "Carlos.Tirado@gmail.com", Telephone = 60352114 },
            new Person() { PersonID = 4, FirstName = "Laura", LastName = "Pari", CI = 7124446, Direction = "Av. Marcelo Terceros No. 112", Mail = "Laura.Pari@gmail.com", Telephone = 76123544 },
            new Person() { PersonID = 5, FirstName = "Leonardo", LastName = "Cadima", CI = 7107808, Direction = "C. Yanacocha N° 326", Mail = "Leonardo.Cadima@gmail.com", Telephone = 68537808 },
            new Person() { PersonID = 6, FirstName = "Lorena", LastName = "Quinteros", CI = 7091170, Direction = "Doble Vía a la Guardia, 4to Anillo, P.O. Box: 3402", Mail = "Lorena.Quinteros@gmail.com", Telephone = 68720459 },
            new Person() { PersonID = 7, FirstName = "Janeth", LastName = "Padilla", CI = 7074532, Direction = "c. Colorados # 80", Mail = "Janeth.Padilla@gmail.com", Telephone = 68903110 },
            new Person() { PersonID = 8, FirstName = "Samuel", LastName = "Corrales", CI = 7057894, Direction = "2º An. Av. El Trompillo # 496", Mail = "Samuel.Corrales@gmail.com", Telephone = 69085761 }
        );
            #endregion                
            #region PresentLists
            context.PresentLists.AddOrUpdate(x => x.PresentListID,
                new PresentList() { PresentListID = 1, Quantity = 25 },
                new PresentList() { PresentListID = 2, Quantity = 25 },
                new PresentList() { PresentListID = 3, Quantity = 25 },
                new PresentList() { PresentListID = 4, Quantity = 25 }
            );
            #endregion
            #region Couples
            context.Couples.AddOrUpdate(x => x.CoupleID,
                new Couple() { CoupleID = 1, Address = "Esteban Arze, Plaza Principal, 14 de Septiembre, Cochabamba", DeliveryDate = new DateTime(2018, 6, 5), HusbandID = 1, WifeID = 2, Latitude = (float)-17.3957997, Longitude = (float)-66.1565556, PresentListID = 1, WeddingDate = new DateTime(2018, 6, 2) },
                new Couple() { CoupleID = 2, Address = "Esteban Arze S-534, Cochabamba", DeliveryDate = new DateTime(2018, 5, 18), HusbandID = 3, WifeID = 4, Latitude = (float)-17.3957997, Longitude = (float)-66.1565556, PresentListID = 2, WeddingDate = new DateTime(2018, 5, 12) },
                new Couple() { CoupleID = 3, Address = "Av Ayacucho, Cochabamba", DeliveryDate = new DateTime(2018, 8, 20), HusbandID = 5, WifeID = 6, Latitude = (float)-17.3957997, Longitude = (float)-66.1565556, PresentListID = 3, WeddingDate = new DateTime(2018, 8, 18) },
                new Couple() { CoupleID = 4, Address = "Calle Uruguay 243, Cochabamba", DeliveryDate = new DateTime(2018, 1, 18), HusbandID = 7, WifeID = 8, Latitude = (float)-17.3949602, Longitude = (float)-66.1574246, PresentListID = 4, WeddingDate = new DateTime(2018, 1, 13) }
            );
            #endregion
            #region Account
            context.Accounts.AddOrUpdate(x => x.AccountID,
                new Account() { AccountID = 1, CoupleID = 1, Name = "AAAOGLGZ7465", Password = "JFH245osi", Token = "QUFBT0dMR1o3NDY1SkZIMjQ1b3Np" },
                new Account() { AccountID = 2, CoupleID = 2, Name = "CSTOLAPI7471", Password = "KJO698tre", Token = "Q1NUT0xBUEk3NDcxS0pPNjk4dHJl" },
                new Account() { AccountID = 3, CoupleID = 3, Name = "LOCALAQS7170", Password = "WER254dda", Token = "TE9DQUxBUVM3MTcwV0VSMjU0ZGRh" },
                new Account() { AccountID = 4, CoupleID = 4, Name = "JHPASLCS7070", Password = "YUT244req", Token = "SkhQQVNMQ1M3MDcwWVVUMjQ0cmVx" }
            );
            #endregion 
            #region Products
            context.Products.AddOrUpdate(x => x.Id,
                new Product() { Id = 1, Name = "X940E / X930E | LED | 4K Ultra HD | High Dynamic Range (HDR) | Smart TV (Android TV)", Description = "See the incredible detail of a 4K HDR picture, brought to life by our Slim Backlight Drive+ and powerful 4K HDR Processor X1 Extreme. Perfectly designed for your wall too, with an ultra-thin profile and versatile swivel mount. | Available in 55in class (54.6in diag), 65in class (64.5in diag), 75in class (74.5in diag)", Brand = "Sony", Category = "White goods", ImageName = "", Price = 1499.99, Stock = 18 },
                new Product() { Id = 2, Name = "4K Ultra HD Blu-ray Player", Description = "Find yourself at the heart of every movie and series. 4K Ultra HD Blu-ray shows everything in finer detail than ever before, so you feel like you're seeing the real thing.", Brand = "SONY", Category = "White goods", ImageName = "", Price = 199.99, Stock = 32 },
                new Product() { Id = 3, Name = "X850E | LED | 4K Ultra HD | High Dynamic Range (HDR) | Smart TV (Android TV)", Description = "Breathtaking pictures meet beautiful design. The new 4K HDR Processor X1 fills every scene with dynamic resolution, color, and brightness for true-to-life viewing. Enjoy all your entertainment, edged in a stunning aluminum frame.", Brand = "SONY", Category = "White goods", ImageName = "", Price = 1099.99, Stock = 16 },
                new Product() { Id = 4, Name = "LG V30 | AT&T", Description = "6.0in QHD + OLED FullVision Display Cine EffectF / 1.6 Glass Camera LensPoint ZoomWide Angle LensesHi - Fi Video Recording", Brand = "LG", Category = "White goods", ImageName = "", Price = 799.99, Stock = 0 },
                new Product() { Id = 5, Name = "2+2 KG TWINWash Washing Machine with True Steam and Turbowash technology", Description = "TWINWash is a washing solution that has never existed before. It is all about efficiency, helping you get more clothes cleaner in less time by washing two separate loads simultaneously. TWINWash Mini, a pedestal type washing machine, helps give special care to your loads of laundry.", Brand = "LG", Category = "White goods", ImageName = "", Price = 1033.99, Stock = 14 },
                new Product() { Id = 6, Name = "SS Microwave", Description = "In line with clients' diverse requirements, we are involved in providing an optimum quality range of SS Microwave.", Brand = "LG", Category = "White goods", ImageName = "", Price = 0.00, Stock = 0 },
                new Product() { Id = 7, Name = "LG 260 L 4 Star Frost-Free Double Door Refrigerator (GL-I292RPZL, Shiny Steel, Inverter Compressor)", Description = "Smart Inverter 3, ice beam door cooling, automatic smart connect and premium florid finish | 1 Year Comprehensive on refrigerator and 9 Years on the Smart Inverter Compressor from LG", Brand = "LG", Category = "White goods", ImageName = "", Price = 2599.99, Stock = 19 },
                new Product() { Id = 8, Name = "2.1ch Soundbar with High-Resolution Audio/Wi-Fi", Description = "Explore new depth and fine detail in every song and movie soundtrack with the HT-NT5’s host of specialized audio components and High-Resolution Audio technologies.", Brand = "SONY", Category = "White goods", ImageName = "", Price = 599.99, Stock = 4 },
                new Product() { Id = 9, Name = "FDR-AX700 4K HDR Camcorder", Description = "Capture life just as you see it in true-to-life 4K3 HDR (HLG) images with the 1.0–type stacked Exmor RS CMOS image sensor. The unrivalled performance of Fast Hybrid AF ensures that autofocus and AF tracking are exceptionally precise, responsive, and reliable, so you'll have every chance to take fantastic shots of fleeting action. With such professional-caliber capabilities so conveniently at your command, there are no limits to how far this Handycam can take your shooting ambitions.", Brand = "SONY", Category = "White goods", ImageName = "", Price = 1899.99, Stock = 11 },
                new Product() { Id = 10, Name = "Notebook 9 Pro 13.3in", Description = "Bring flexibility to work with the powerful and versatile Samsung Notebook 9 Pro. Easily switch between typing on the keyboard, writing with the intuitive S Pen, and navigating the brilliant touchscreen. And do it all at once with an ultra-fast Intel Core i7 processor. The Samsung Notebook 9 Pro keeps up with all the ways you work.", Brand = "Samsung", Category = "White goods", ImageName = "", Price = 1149.99, Stock = 6 },
                new Product() { Id = 11, Name = "Notebook 9 Pro 15in (16GB RAM)", Description = "Bring flexibility to work with the powerful and versatile Samsung Notebook 9 Pro. Easily switch between typing on the keyboard, writing with the intuitive S Pen, and navigating the brilliant touchscreen. And do it all at once with an ultra-fast Intel Core i7 processor and a Radeon 540 graphics card. The Samsung Notebook 9 Pro keeps up with all the ways you work.", Brand = "Samsung", Category = "White goods", ImageName = "", Price = 1299.99, Stock = 8 },
                new Product() { Id = 12, Name = "Louis Philippe full bed - gray", Description = "Shapely curves and classic styling make the Louis Philippe full-size bed a wonderful choice for your bedroom! Made of quality wood solids and veneers, this timeless piece is crafted in a beautiful gray finish accented with a beautiful sleigh style headboard and footboard to complete the look! In stock and on sale now! Saving you MORE on the looks you LOVE! Home Furniture! Welcome Home.", Brand = "Louis Philippe", Category = "Furnitures", ImageName = "", Price = 299.99, Stock = 9 },
                new Product() { Id = 13, Name = "Louis Philippe dresser/ mirror - gray", Description = "Shapely curves and classic styling make the Louis Philippe dresser and mirror a wonderful choice for your bedroom! Made of quality wood solids and veneers, this timeless piece is crafted in a beautiful gray finish accented with opulent antiqued brass hardware and plenty of storage space! In stock and on sale now! Saving you MORE on the looks you LOVE! Home Furniture! Welcome Home.", Brand = "Louis Philippe", Category = "Furnitures", ImageName = "", Price = 299.99, Stock = 2 },
                new Product() { Id = 14, Name = "Louis Philippe nightstand - gray", Description = "Shapely curves and classic styling make the Louis Philippe nightstand a wonderful choice for your bedroom! Made of quality wood solids and veneers, this timeless piece is crafted in a beautiful gray finish accented with opulent antiqued brass hardware and plenty of storage space! In stock and on sale now! Saving you MORE on the looks you LOVE! Home Furniture! Welcome Home.", Brand = "Louis Philippe", Category = "Furnitures", ImageName = "", Price = 99.99, Stock = 15 },
                new Product() { Id = 15, Name = "Marseille Dresser with Mirror", Description = "Introducing the Marseille Collection Dresser with Mirror​. Experience true classic traditional Louis Philippe styling but with an updated look! You’ll love the elegant double moldings and the shaped overlays along with the antiqued distressed mid-tone cherry finish and antiqued gold-finished knobs! Other features include stylish bracket feet and a triple layered top along with side mounted metal drawer glides and luxurious felt lined top drawers.", Brand = "Marseille ", Category = "Furnitures", ImageName = "", Price = 499.99, Stock = 12 },
                new Product() { Id = 16, Name = "PlayStation 4 Pro", Description = "The PS4 Pro has all the power and performance you need.", Brand = "Sony", Category = "Home entertainment", ImageName = "", Price = 299.99, Stock = 27 },
                new Product() { Id = 17, Name = "EastPoint Sports Masterton Billiard Table, 87-Inch", Description = "Traditional claw leg billiard table featuring Scratch resistant luster long finish to resist wear & tear", Brand = "EastPoint", Category = "Home entertainment", ImageName = "", Price = 499.99, Stock = 11 },
                new Product() { Id = 18, Name = "Sony - PlayStation VR The Elder Scrolls V: Skyrim VR Bundle", Description = "Surround yourself with the sights and sounds of a favorite gaming franchise with this PlayStation VR Skyrim bundle. Including everything from VR goggles and a camera to two movie controllers, this setup offers plug-and-play compatibility with all PlayStation 4 consoles. This PlayStation VR Skyrim bundle includes a copy of The Elder Scrolls V: Skyrim VR, so you can walk the world of Dragonborn.", Brand = "Sony", Category = "Home entertainment", ImageName = "", Price = 399.99, Stock = 22 },
                new Product() { Id = 19, Name = "Logitech - G29 Driving Force Racing Wheel for PlayStation 3 and PlayStation 4 - Black", Description = "", Brand = "Logitech", Category = "Home entertainment", ImageName = "", Price = 399.99, Stock = 12 },
                new Product() { Id = 20, Name = "Sony - Platinum Wireless 7.1 Virtual Surround Sound Gaming Headset for PlayStation 4 - Black", Description = "Enjoy nuanced sound as you play your favorite games wearing this Platinum Wireless Headset. A dual microphone lets you share strategies with other players, and the extended-life battery delivers clear sound through long gaming sessions. With multi-device capability, this Platinum Wireless Headset works with your PS4 gaming console and your PC.", Brand = "Sony", Category = "Home entertainment", ImageName = "", Price = 159.99, Stock = 32 },
                new Product() { Id = 21, Name = "PlayStationVR Aim Controller Farpoint Bundle - PlayStation 4", Description = "Gamers Club Unlocked", Brand = "sony", Category = "Home entertainment", ImageName = "", Price = 79.99, Stock = 34 },
                new Product() { Id = 22, Name = "Rachael Ray - Cucina 14in Skillet with Helper Handle - Gray/Cranberry Red", Description = "Create delightful sautés and fried foods with this Rachael Ray Cucina 87631 14in skillet that features a helper handle to aid moving the pan between kitchen stations.The sturdy aluminum construction provides even heat for consistent cooking results.", Brand = "Rachael Ray", Category = "Housewares", ImageName = "", Price = 45.99, Stock = 56 },
                new Product() { Id = 23, Name = "Marseille Queen Bed", Description = "Introducing the Marseille Queen Size Bed. Experience true classic traditional Louis Philippe styling but with an updated look! You’ll love the elegant sleigh bed that features a stylish sunburst veneer pattern on the headboard and double moldings with shaped overlays along with an antiqued distressed mid-tone cherry finish and stylish bracket feet to complete the look!", Brand = "Marseille", Category = "Furnitures", ImageName = "", Price = 449.99, Stock = 0 },
                new Product() { Id = 24, Name = "Marseille King Bed", Description = "Introducing the Marseille King Size Bed​. Experience true classic traditional Louis Philippe styling but with an updated look! You’ll love the elegant sleigh bed that features a stylish sunburst veneer pattern on the headboard and double moldings with shaped overlays along with an antiqued distressed mid-tone cherry finish and stylish bracket feet to complete the look!", Brand = "Marseille", Category = "Furnitures", ImageName = "", Price = 649.99, Stock = 0 },
                new Product() { Id = 25, Name = "Marseille Chest of Drawers", Description = "ntroducing the Marseille chest. Experience true classic traditional Louis Philippe styling but with an updated look! You’ll love the elegant double moldings and the shaped overlays. Other features are the antiqued distressed mid-tone cherry finish and antiqued gold-finished knobs, stylish bracket feet and a triple layered top along with side mounted metal drawer glides and the luxurious felt lined top drawer. ", Brand = "Marseille", Category = "Furnitures", ImageName = "", Price = 399.99, Stock = 0 },
                new Product() { Id = 26, Name = "Marseille Nightstand", Description = "Introducing the Marseille Nightstand. Experience true classic traditional Louis Philippe styling but with an updated look! You’ll love the elegant double moldings and the shaped overlays. Other features are the antiqued distressed mid-tone cherry finish and antiqued gold-finished knobs, stylish bracket feet and a triple layered top along with side mounted metal drawer glides and the luxurious felt lined top drawer. In Stock.", Brand = "Marseille", Category = "Furnitures", ImageName = "", Price = 179.99, Stock = 22 },
                new Product() { Id = 27, Name = "Thrustmaster - T.Flight Hotas 4 Joystick", Description = "The T.Flight Hotas 4, official joystick on PLAYSTATION 4 and compatible with PC, provides a high level of realism: its stick features a large hand rest and easily accessible rapid-fire trigger. The life-size, detachable throttle provides super-responsive power. The dual rudder system works by rotating the handle (with integrated locking system) or by progressive tilting lever. T.Flight Hotas 4 is also programmable, mappable and features an internal memory to save the latest programming, even when disconnected.", Brand = "Thrustmaster", Category = "Home entertainment", ImageName = "", Price = 69.99, Stock = 29 },
                new Product() { Id = 28, Name = "Play In The City Pool Table 8Ft. X 4Ft Green American Style Billiard", Description = "Material: Highly Density Quality Wood & HardBoard with Scratch proof PVC, Height adjustable Chrome plated leg levelers with Chromed corners.", Brand = "American ", Category = "Housewares", ImageName = "", Price = 899.99, Stock = 11 },
                new Product() { Id = 29, Name = "Magic Bullet - Blender - Silver/Black", Description = "Magic Bullet Blender: Mix drinks and make smooth shakes with this blender, which features pulse, purée and chop functions for a variety of drinks. The included cups, lids and rings are top-shelf dishwasher safe for easy cleaning.", Brand = "Magic Bullet", Category = "Housewares", ImageName = "", Price = 39.99, Stock = 20 },
                new Product() { Id = 30, Name = "Cuisinart - Chef's Classic 7-Piece Cookware Set - Black", Description = "This Cuisinart Chef's Classic 66-7 7-piece cookware set features hard anodized exteriors that ensure durability and Quantanium nonstick cooking surfaces that easily release foods to simplify cleanup.", Brand = "Cuisinart", Category = "Housewares", ImageName = "", Price = 99.99, Stock = 28 },
                new Product() { Id = 31, Name = "KitchenAid - KKFTR14SL Classic 14-Piece Knife Set - Silver", Description = "Simplify food preparation with this 14-piece KitchenAid cutlery set. The forged full-tang blades are made of German stainless steel for durability, and the painted wood knife block sports an integrated knife sharpener to make maintaining the blade edges easy. Poultry shears are included with this KitchenAid cutlery set for added versatility.", Brand = "KitchenAid", Category = "Housewares", ImageName = "", Price = 99.99, Stock = 18 },
                new Product() { Id = 32, Name = "Cuisinart - Aveline 20-Piece Flatware Set - Stainless steel", Description = "Complete your table settings with this Cuisinart Aveline flatware set. The 20-piece set includes service for four, and the heavy-gauge stainless steel holds up to daily use at family dinners or special events. This Cuisinart Aveline flatware set complements most table settings with the simple design on its salad and dessert forks, knives, soup spoons and teaspoons.", Brand = "Cuisinart", Category = "Housewares", ImageName = "", Price = 46.99, Stock = 100 },
                new Product() { Id = 33, Name = "Plantronics - RIG 4VR Wired Stereo Gaming Headset for Playstation VR - White", Description = "Play all day in comfort with this Plantronics RIG 4VR headset for PlayStation VR. Noise-cancellation technology lets you immerse yourself in virtual worlds without being drawn out by daily disruptions. This Plantronics RIG 4VR headset offers padded earcups and headband for comfort, and the removable boom mic and cables offer versatile use with other controllers.", Brand = "Plantronics", Category = "Home entertainment", ImageName = "", Price = 69.99, Stock = 36 },
                new Product() { Id = 34, Name = "KBA MILITARY SOCCER TABLE or FOOSBALL TABLE", Description = "Details 1.IMPORTED TABLE MADE BY MDF BOARD. 2.MULTI COLOUR PLAYERS 3.STRAIGHT LEGS 4.HEAVY DUTY 5.3 BALLS 6.FOUR ADJUSTER TO MAINTAIN BALANCE 7.WEIGHT 25 KG APPROX. 8.SIZE 2 FEET X 4 FEET 9", Brand = "MILITARY", Category = "Home entertainment", ImageName = "", Price = 259.99, Stock = 19 },
                new Product() { Id = 35, Name = "Logitech - Driving Force Shifter for Windows, Xbox One and PlayStation 4 - Black/Silver", Description = "When you careen around a hairpin curve, mow down a straightaway or tear up the mountainside, having precise control over your vehicle is crucial. This Logitech Driving Force Shifter allows you to enjoy an authentic racing experience on your PlayStation 4, Xbox One or PC with its solid-steel shaft and hand-stitched leather construction. The six-speed H-pattern shifter with push-down reverse smoothly moves from gear to gear and clicks into each one for accurate shifting. Mount the shifter to your table or racing rig to enjoy stability during even the most heated racing maneuvers. Shift your racing experience into another gear with this Driving Force Shifter.", Brand = "Logitech", Category = "Home entertainment", ImageName = "", Price = 59.99, Stock = 20 },
                new Product() { Id = 36, Name = "Keurig - K50 Classic Series Coffeemaker - Black", Description = "Treat yourself to freshly brewed individual cups of your favorite hot beverages with this Keurig K50 brewer. The compact size takes up minimal space on your counters, and the removable drip tray prevents splashes and spills. Featuring a 48-ounce water reservoir, this Keurig K50 brewer is always ready to brew delicious drinks.", Brand = "Keurig", Category = "Home entertainment", ImageName = "", Price = 89.99, Stock = 42 },
                new Product() { Id = 37, Name = "Oster - Inspire 2-Slice Wide-Slot Toaster - Black", Description = "Breakfast is the most important meal of the day and this toaster with extra-wide slots and a choice of 7 toasting shades will help you start the day off right.", Brand = "Oster", Category = "Housewares", ImageName = "", Price = 19.99, Stock = 24 },
                new Product() { Id = 38, Name = "Bella - Pro Series 6 - Slice Toaster Oven - Black stainless steel", Description = "Serve hot breakfast and snacks with this six-slice Bella Pro Series toaster oven. Its quartz and steel heating elements let you efficiently cook and brown food, and it has nine preprogrammed functions for warming, defrosting and baking. With a 24L capacity, this Bella Pro Series toaster oven fits a 12-inch pizza or 8 x 12-inch baking pan.", Brand = "Bella", Category = "Housewares", ImageName = "", Price = 69.99, Stock = 15 },
                new Product() { Id = 39, Name = "Oster - 10-Speed Blender - Black", Description = "Prepare your favorite fruit smoothies and milkshakes with this 10-speed blender. Cleanup is a snap with the Easy Clean feature, saving you time.", Brand = "Oster", Category = "Housewares", ImageName = "", Price = 17.99, Stock = 50 },
                new Product() { Id = 40, Name = "Bombay Sofa Table", Description = "Give your home an opulent Old World flair with the beautiful Bombay oval sofa table by world famous Standard! Features include antiqued bronze finished metal S-scrolled legs and a burnished dark cherry finished top with tempered glass over a scrolled metal grill complete with a matching lower metal-banded shelf. Saving you MORE on the LOOKS you love! Home Furniture! Welcome Home.", Brand = "Hillsboro", Category = "Housewares", ImageName = "", Price = 299.99, Stock = 32 },
                new Product() { Id = 41, Name = "Bombay Cocktail Table", Description = "Give your home an opulent Old World flair with the beautiful Bombay oval cocktail table by world famous Standard! Features include antiqued bronze finished metal S-scrolled legs and a burnished dark cherry finished top with tempered glass over a scrolled metal grill complete with a matching lower metal-banded shelf. Saving you MORE on the LOOKS you love! Home Furniture! Welcome Home.", Brand = "Hillsboro", Category = "Furnitures", ImageName = "", Price = 229.99, Stock = 25 },
                new Product() { Id = 42, Name = "Bombay End Table", Description = "Give your home an opulent Old World flair with the beautiful Bombay round end table by world famous Standard! Features include antiqued bronze finished metal S-scrolled legs and a burnished dark cherry finished top with tempered glass over a scrolled metal grill complete with a matching lower metal-banded shelf. Saving you MORE on the LOOKS you love! Home Furniture! Welcome Home.", Brand = "Hillsboro", Category = "Furnitures", ImageName = "", Price = 299.99, Stock = 18 },
                new Product() { Id = 43, Name = "Hillsboro Dresser/Mirror", Description = "Grace your bedroom today with the elegance of the Hillsboro dresser and mirror and transform your bedroom into a tranquil sanctuary night after blissful night! Crafted of cherry and ash burl veneers covered in a rich dark sable finish complete with exquisite ornate detailing,  an artistically designed arched mirror, distinctive round knobs and 9 drawers of convenient storage space. In stock and on sale now! Home Furniture! Welcome Home.", Brand = "Hillsboro", Category = "Furnitures", ImageName = "", Price = 999.99, Stock = 39 },
                new Product() { Id = 44, Name = "CX455 Handycam with Exmor R CMOS sensor", Description = "Aim for high impact in high definition with a Sony Full HD Handycam camcorder that’s ready for action wherever you go. Shoot movies of everything, from wide open scenes to quick, intimate glances, with sophisticated features that make it simple to capture the feeling of the moment in great detail. ", Brand = "SONY", Category = "White goods", ImageName = "", Price = 399.99, Stock = 27 },
                new Product() { Id = 45, Name = "Blu-ray Home Theater System with Bluetooth", Description = "Simply touch your NFC-enabled smartphone or tablet to your Home Theater system to mirror your videos, photos, and more on your TV.", Brand = "SONY", Category = "White goods", ImageName = "", Price = 499.99, Stock = 38 },
                new Product() { Id = 46, Name = "4K Upscale Blu-ray Disc Player", Description = "See every precise detail with 4K upscaling of your favorite DVDs and Blu-ray Discs. Hear sound as the artist intended in studio-quality High-Resolution Audio. With the BDP-S7200 4K Blu-ray player, subtlety takes center stage, transforming movies, TV shows, and music. And with super Wi-Fi, you can stream seamlessly from the Web too.", Brand = "SONY", Category = "White goods", ImageName = "", Price = 179.99, Stock = 60 },
                new Product() { Id = 47, Name = "Galaxy Tab S3 9.7in (S Pen included), Black", Description = "The revolutionary S Pen has true-to-life pressure and angle sensitivity with the intelligence to translate, magnify, navigate and create with a full pallete of brush and pen types. And just like a real pen, it never needs to be charged.", Brand = "Samsung", Category = "White goods", ImageName = "", Price = 499.99, Stock = 52 },
                new Product() { Id = 48, Name = "Galaxy Tab E 8in 32GB(Verizon)", Description = "he perfect combinations of versatility and value, the Galaxy Tab E 32GB makes every day better. Catch up on shows.Check social medial.Snap photos.From where you go – and all on a tablet that’s simple to navigate.", Brand = "Samsung", Category = "White goods", ImageName = "", Price = 321.99, Stock = 26 },
                new Product() { Id = 49, Name = "DV9900 7.5 cu. ft. FlexDry Gas Dryer", Description = "Two dryers in one lets you dry delicates and everyday garments at the same time, or independently. By combining a conventional large capacity dryer with a delicate dryer, you can dry everyday clothes and delicates that need gentle care to keep your items in great condition.", Brand = "Samsung", Category = "White goods", ImageName = "", Price = 1999.00, Stock = 21 },
                new Product() { Id = 50, Name = "DV8750 7.4 cu. ft. Gas Dryer with Integrated Touch Controls", Description = "Eco-friendly and energy-efficient, Meets the strict 2017 energy efficiency specifications and standards.*", Brand = "Samsung", Category = "White goods", ImageName = "", Price = 1299.00, Stock = 13 }
            );
            #endregion                
            #region Presents

            context.Presents.AddOrUpdate(x => x.PresentID,
                new Present() { PresentID = 1, PresentListID = 1, ProductID = 1, Status = false },
                new Present() { PresentID = 2, PresentListID = 1, ProductID = 3, Status = false },
                new Present() { PresentID = 3, PresentListID = 1, ProductID = 5, Status = true },
                new Present() { PresentID = 4, PresentListID = 1, ProductID = 7, Status = false },
                new Present() { PresentID = 5, PresentListID = 1, ProductID = 9, Status = false },
                new Present() { PresentID = 6, PresentListID = 1, ProductID = 11, Status = false },
                new Present() { PresentID = 7, PresentListID = 1, ProductID = 13, Status = true },
                new Present() { PresentID = 8, PresentListID = 1, ProductID = 15, Status = false },
                new Present() { PresentID = 9, PresentListID = 1, ProductID = 17, Status = false },
                new Present() { PresentID = 10, PresentListID = 1, ProductID = 19, Status = false },
                new Present() { PresentID = 11, PresentListID = 1, ProductID = 21, Status = true },
                new Present() { PresentID = 12, PresentListID = 1, ProductID = 23, Status = false },
                new Present() { PresentID = 13, PresentListID = 1, ProductID = 25, Status = true },
                new Present() { PresentID = 14, PresentListID = 1, ProductID = 27, Status = false },
                new Present() { PresentID = 15, PresentListID = 1, ProductID = 29, Status = true },
                new Present() { PresentID = 16, PresentListID = 1, ProductID = 31, Status = false },
                new Present() { PresentID = 17, PresentListID = 1, ProductID = 33, Status = false },
                new Present() { PresentID = 18, PresentListID = 1, ProductID = 35, Status = true },
                new Present() { PresentID = 19, PresentListID = 1, ProductID = 37, Status = false },
                new Present() { PresentID = 20, PresentListID = 1, ProductID = 39, Status = false },
                new Present() { PresentID = 21, PresentListID = 1, ProductID = 41, Status = true },
                new Present() { PresentID = 22, PresentListID = 1, ProductID = 43, Status = false },
                new Present() { PresentID = 23, PresentListID = 1, ProductID = 45, Status = true },
                new Present() { PresentID = 24, PresentListID = 1, ProductID = 47, Status = true },
                new Present() { PresentID = 25, PresentListID = 1, ProductID = 49, Status = false }
            );

            context.Presents.AddOrUpdate(x => x.PresentID,
                new Present() { PresentID = 26, PresentListID = 3, ProductID = 2, Status = true },
                new Present() { PresentID = 27, PresentListID = 3, ProductID = 4, Status = true },
                new Present() { PresentID = 28, PresentListID = 3, ProductID = 6, Status = true },
                new Present() { PresentID = 29, PresentListID = 3, ProductID = 8, Status = true },
                new Present() { PresentID = 30, PresentListID = 3, ProductID = 10, Status = true },
                new Present() { PresentID = 31, PresentListID = 3, ProductID = 12, Status = false },
                new Present() { PresentID = 32, PresentListID = 3, ProductID = 14, Status = true },
                new Present() { PresentID = 33, PresentListID = 3, ProductID = 16, Status = false },
                new Present() { PresentID = 34, PresentListID = 3, ProductID = 18, Status = false },
                new Present() { PresentID = 35, PresentListID = 3, ProductID = 20, Status = false },
                new Present() { PresentID = 36, PresentListID = 3, ProductID = 22, Status = true },
                new Present() { PresentID = 37, PresentListID = 3, ProductID = 24, Status = false },
                new Present() { PresentID = 38, PresentListID = 3, ProductID = 26, Status = true },
                new Present() { PresentID = 39, PresentListID = 3, ProductID = 28, Status = false },
                new Present() { PresentID = 40, PresentListID = 3, ProductID = 30, Status = true },
                new Present() { PresentID = 41, PresentListID = 3, ProductID = 32, Status = false },
                new Present() { PresentID = 42, PresentListID = 3, ProductID = 34, Status = false },
                new Present() { PresentID = 43, PresentListID = 3, ProductID = 36, Status = true },
                new Present() { PresentID = 44, PresentListID = 3, ProductID = 38, Status = false },
                new Present() { PresentID = 45, PresentListID = 3, ProductID = 40, Status = false },
                new Present() { PresentID = 46, PresentListID = 3, ProductID = 42, Status = true },
                new Present() { PresentID = 47, PresentListID = 3, ProductID = 44, Status = false },
                new Present() { PresentID = 48, PresentListID = 3, ProductID = 46, Status = true },
                new Present() { PresentID = 49, PresentListID = 3, ProductID = 48, Status = true },
                new Present() { PresentID = 50, PresentListID = 3, ProductID = 50, Status = false }
            );
            #endregion
            #region Dedicatories
            context.Dedicatories.AddOrUpdate(x => x.DedicatoryID,
                new Models.Dedicatory() { DedicatoryID = 1, Name = "Fred Astaire and Ginger Rogers", Message = "", PresentID = 3 },
                new Models.Dedicatory() { DedicatoryID = 2, Name = "Henry and Clare", Message = "Marriage is the combination of two hearts and two souls, which join each other on this special day of your wedding. Wishing you two a very happy and blessed married life!", PresentID = 7 },
                new Models.Dedicatory() { DedicatoryID = 3, Name = "James and Lilly", Message = "Young family is like a baby: it needs love, attention and care to become strong and beautiful. Congratulations on your wedding!", PresentID = 11 },
                new Models.Dedicatory() { DedicatoryID = 4, Name = "Joan and Robee", Message = "Take care of each other, because since now you’re the closest people on the planet. Congratulations on your wedding!", PresentID = 13 },
                new Models.Dedicatory() { DedicatoryID = 5, Name = "Jack and Sally", Message = "Wonderful newly weds, you’re the fines couple I’ve ever seen and I’m sure you deserve a happy marriage life. Congratulations on the wedding!", PresentID = 15 },
                new Models.Dedicatory() { DedicatoryID = 6, Name = "Peter", Message = "May love, harmony and understanding be aims of your marriage union! Congratulations!", PresentID = 18 },
                new Models.Dedicatory() { DedicatoryID = 7, Name = "Lucia", Message = "I congratulate you on this happy occasion and wish a lot of happy years together!", PresentID = 21 },
                new Models.Dedicatory() { DedicatoryID = 8, Name = "Lois and Donald", Message = "Family life isn’t easy, so be ready to protect your family happiness. It’s worth it. Congratulations on your wedding!", PresentID = 23 },
                new Models.Dedicatory() { DedicatoryID = 9, Name = "Lucious", Message = "Now and forever, may your wonderful family never encounter grief and sorrow. Have a spectacular life together!", PresentID = 24 },
                new Models.Dedicatory() { DedicatoryID = 10, Name = "Frederic and Tiffany", Message = "Nothing can be better than starting your own family. Appreciate and honour it your whole life. Congratulations on the wedding!", PresentID = 26 },
                new Models.Dedicatory() { DedicatoryID = 11, Name = "Anonimous", Message = "", PresentID = 27 },
                new Models.Dedicatory() { DedicatoryID = 12, Name = "Lou", Message = "The time flies and things change, but I wish that your love for each other would stay unchangeable. Congratulations!", PresentID = 28 },
                new Models.Dedicatory() { DedicatoryID = 13, Name = "Martin and Patrice", Message = "", PresentID = 29 },
                new Models.Dedicatory() { DedicatoryID = 14, Name = "Marshal", Message = "", PresentID = 30 },
                new Models.Dedicatory() { DedicatoryID = 15, Name = "Ted and Tracy", Message = "You’ve just got married, but I’m already looking forward to seeing your pretty kids. Congratulations, dear newly weds!", PresentID = 32 },
                new Models.Dedicatory() { DedicatoryID = 16, Name = "Loretta", Message = "", PresentID = 36 },
                new Models.Dedicatory() { DedicatoryID = 17, Name = "Sheldon and Lory", Message = "Make your home and family be the safest place on Earth. Congratulations on your wedding!", PresentID = 38 },
                new Models.Dedicatory() { DedicatoryID = 18, Name = "Leonard", Message = "Wishing this day be the start of the best time of your life.The most heartfelt congratulations to Bride and Groom!", PresentID = 40 },
                new Models.Dedicatory() { DedicatoryID = 19, Name = "Teodore", Message = "You’ve made me believe in true love. And I hope my belief will be unwavering forever, because it seems like you’ll stay together till the end. Congratulations!", PresentID = 43 },
                new Models.Dedicatory() { DedicatoryID = 20, Name = "Lucas", Message = "We’re all happy today. May this happiness last forever! Congratulations on your wedding!", PresentID = 46 },
                new Models.Dedicatory() { DedicatoryID = 21, Name = "Penny and Julio", Message = "A young family is always full of plans and dreams and I wish that they would come true. Congratulations!", PresentID = 48 },
                new Models.Dedicatory() { DedicatoryID = 22, Name = "No name", Message = "", PresentID = 49 }
            );
            #endregion
        }
    }
}
